spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSl=false

    username: devuser
    password: ************

  mail:
    host: smtp.gmail.com
    port: 587
    username: user@gmail.com
    password: **************
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  #JPA Settings
  jpa.hibernate.ddl_auto: update
