spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSl=false

    username: devuser
    password: cTnVLh3JJ9Uk6Z

  mail:
    host: smtp.gmail.com
    port: 587
    username: suyashpbe@gmail.com
    password: egcyoqtfmbdresuy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  #JPA Settings
  jpa.hibernate.ddl_auto: update
